
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rightchain
    env_file:
      - .env.local
    depends_on:
      - database
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}
    restart: always
    volumes:
      - rightchain-storage:${STORAGE_PATH}

  database:
    image: postgres:latest
    container_name: rightchain-database
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: -p ${DB_PORT}
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: always
    volumes:
      - rightchain-database:/var/lib/postgresql/data

volumes:
  rightchain-storage:
  rightchain-database:
