
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rightchain
    env_file:
      - .env.local
    depends_on:
      - redis
      - database
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}
    restart: always
    volumes:
      - rightchain-storage:${BASE_PATH}

  database:
    image: postgres:latest
    container_name: rightchain-database
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: -p ${DB_PORT}
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: always
    volumes:
      - rightchain-database:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: rightchain-redis
    command: --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD}
    expose:
      - ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - rightchain-redis:/data
    restart: always

volumes:
  rightchain-storage:
  rightchain-database:
  rightchain-redis: