server:
  port: ${SPRING_PORT}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

  verification:
    code:
      expiration: 1800 #

  jwt:
    secret: ${JWT_SECRET}

  file:
    upload-dir: ${STORAGE_PATH}

  chain:
    api-token: ${API_TOKEN}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URI}
            scope:  #scope openId, google만 사용하면 설정 안하고 default 사용해도됨.
              - email
              - profile

  org:
    gradle:
      caching: true

  messages:
    basename: messages/validation, messages/error

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
springdoc:
  swagger-ui:
    path: /docs